### ISSUE TITLE
New Fortune Pool mechanic introduced in Starter Kit

### ISSUE THREAD

**Issue by Verencius** [fh-fvtt/zweihander#168]
New Fortune Pool mechanic introduced in Starter Kit

At the beginning of every new session, pull out the chipboard tokens from the Starter Kit or coins, equal to the number of players plus the GM in the middle of the table. For example, if there is 1 GM and 3 players, there should be 4 coins. Then, put a bowl in front of the GM (Misfortune Pool) and another shared bowl in front of the players (Fortune Pool).

The GM immediately takes one of these coins and adds it to their Misfortune Pool. Each player then rolls 1D6 Chaos Die. For every face '1-5', take a coin from the stack and put it into the shared player Fortune Pool. For every result of face '6', a coin from the stack goes into the GM’s Misfortune Pool.

**Comment by Re4XN** [comment]
Not sure if this _needs_ a special implementation. It seems a simple thing to do a the beginning of a session: assuming 4 players + GM, roll 4d6 (since 1 coin always goes to GM), count 6s and transfer those to the GM by using the already built Fortune Pool application.

What is the expectation with this issue? I might be missing something.

**Comment by Re4XN** [comment]
Closing as no further clarification provided.
